;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters=
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Actor.Action",DevComment="")
+GameplayTagList=(Tag="Actor.Action.Rotate",DevComment="")
+GameplayTagList=(Tag="Actor.State.IsRotating",DevComment="")
+GameplayTagList=(Tag="Character.Action.AttackHitCheck",DevComment="")
+GameplayTagList=(Tag="Character.State.Changeposing",DevComment="")
+GameplayTagList=(Tag="Character.State.Hit",DevComment="")
+GameplayTagList=(Tag="Character.State.IsAiming",DevComment="")
+GameplayTagList=(Tag="Character.State.IsCrouch",DevComment="")
+GameplayTagList=(Tag="Character.State.IsDead",DevComment="")
+GameplayTagList=(Tag="Character.State.IsFiring",DevComment="")
+GameplayTagList=(Tag="Character.State.IsJumping",DevComment="")
+GameplayTagList=(Tag="Character.State.IsProne",DevComment="")
+GameplayTagList=(Tag="Character.State.IsReloading",DevComment="")
+GameplayTagList=(Tag="Character.State.IsShoulder",DevComment="")
+GameplayTagList=(Tag="Character.State.IsSprint",DevComment="")
+GameplayTagList=(Tag="Character.State.IsStratagemInputMode",DevComment="")
+GameplayTagList=(Tag="Character.State.Knockback",DevComment="")
+GameplayTagList=(Tag="Character.State.Ragdoll",DevComment="")
+GameplayTagList=(Tag="Cost.Stamina",DevComment="")
+GameplayTagList=(Tag="Data.Attribute",DevComment="")
+GameplayTagList=(Tag="Data.Attribute.CrawlingSpeed",DevComment="")
+GameplayTagList=(Tag="Data.Attribute.CrouchSpeed",DevComment="")
+GameplayTagList=(Tag="Data.Attribute.CurrentHealth",DevComment="")
+GameplayTagList=(Tag="Data.Attribute.CurrentStamina",DevComment="")
+GameplayTagList=(Tag="Data.Attribute.MaxHealth",DevComment="")
+GameplayTagList=(Tag="Data.Attribute.MaxStamina",DevComment="")
+GameplayTagList=(Tag="Data.Attribute.SprintSpeed",DevComment="")
+GameplayTagList=(Tag="Data.Attribute.WalkSpeed",DevComment="")
+GameplayTagList=(Tag="Data.Damage.Projectile",DevComment="")
+GameplayTagList=(Tag="Data.DotDamage",DevComment="")
+GameplayTagList=(Tag="Data.DotDamage.Duration",DevComment="")
+GameplayTagList=(Tag="Data.DotDamage.TickDamage",DevComment="")
+GameplayTagList=(Tag="Data.Knockback",DevComment="")
+GameplayTagList=(Tag="Data.Knockback.Hit",DevComment="")
+GameplayTagList=(Tag="Data.Knockback.Ragdoll",DevComment="")
+GameplayTagList=(Tag="Data.Projectile.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Projectile.DotDamage",DevComment="")
+GameplayTagList=(Tag="Data.Projectile.StatusEffectDuration",DevComment="")
+GameplayTagList=(Tag="Event.PlayerHUD",DevComment="")
+GameplayTagList=(Tag="Event.PlayerHUD.AmmoChange",DevComment="")
+GameplayTagList=(Tag="Event.PlayerHUD.CapacityChange",DevComment="")
+GameplayTagList=(Tag="Event.PlayerHUD.HealthChange",DevComment="")
+GameplayTagList=(Tag="Event.StratagemHUD.Active",DevComment="")
+GameplayTagList=(Tag="Event.StratagemHUD.AddCommand",DevComment="")
+GameplayTagList=(Tag="Event.StratagemHUD.Deactive",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Block.Bullet_Heavy",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Block.Bullet_Light",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Block.Bullet_Medium",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Block.Hellpod",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Explode.Bomb_Heavy",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Explode.Bomb_Light",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Explode.Bomb_Medium",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FootStep.Default",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FootStep.Metal",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FootStep.Stone",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FootStep.Wood",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Bullet_Heavy",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Bullet_Light",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Bullet_Medium",DevComment="")
+GameplayTagList=(Tag="Input.Alt",DevComment="")
+GameplayTagList=(Tag="Input.C",DevComment="")
+GameplayTagList=(Tag="Input.Ctrl",DevComment="")
+GameplayTagList=(Tag="Input.Down",DevComment="")
+GameplayTagList=(Tag="Input.E",DevComment="")
+GameplayTagList=(Tag="Input.Left",DevComment="")
+GameplayTagList=(Tag="Input.MouseL",DevComment="")
+GameplayTagList=(Tag="Input.MouseR",DevComment="")
+GameplayTagList=(Tag="Input.Num_1",DevComment="")
+GameplayTagList=(Tag="Input.Num_2",DevComment="")
+GameplayTagList=(Tag="Input.Num_3",DevComment="")
+GameplayTagList=(Tag="Input.Num_4",DevComment="")
+GameplayTagList=(Tag="Input.Q",DevComment="")
+GameplayTagList=(Tag="Input.R",DevComment="")
+GameplayTagList=(Tag="Input.Right",DevComment="")
+GameplayTagList=(Tag="Input.Shift",DevComment="")
+GameplayTagList=(Tag="Input.Space",DevComment="")
+GameplayTagList=(Tag="Input.Up",DevComment="")
+GameplayTagList=(Tag="Input.V",DevComment="")
+GameplayTagList=(Tag="Input.X",DevComment="")
+GameplayTagList=(Tag="Input.Z",DevComment="")
+GameplayTagList=(Tag="Regen.Stamina",DevComment="")
+GameplayTagList=(Tag="Sound.Impact.Bullet",DevComment="")
+GameplayTagList=(Tag="Trigger.Aiming",DevComment="")
+GameplayTagList=(Tag="Trigger.Attack",DevComment="")
+GameplayTagList=(Tag="Trigger.Crouch",DevComment="")
+GameplayTagList=(Tag="Trigger.Dead",DevComment="")
+GameplayTagList=(Tag="Trigger.Hit",DevComment="")
+GameplayTagList=(Tag="Trigger.Prone",DevComment="")
+GameplayTagList=(Tag="Trigger.Ragdoll",DevComment="")
+GameplayTagList=(Tag="Trigger.RegenStamina",DevComment="")
+GameplayTagList=(Tag="Trigger.Reload",DevComment="")
+GameplayTagList=(Tag="Trigger.Shoulder",DevComment="")
+GameplayTagList=(Tag="Trigger.Sprint",DevComment="")
+GameplayTagList=(Tag="Trigger.StratagemInputMode",DevComment="")

