
#pragma once

#include "CoreMinimal.h"

#define HDCOLLISION_PROFILE_CAPSULE      TEXT("HDCapsule")
#define HDCOLLISION_PROFILE_PLAYER       TEXT("HDPlayer")
#define HDCOLLISION_PROFILE_PROJECTILE   TEXT("HDProjectile")
#define HDCOLLISION_PROFILE_TRIGGER      TEXT("HDTrigger")
#define HDCOLLISION_PROFILE_HELLPOD		 TEXT("HDHellpod")

#define HDCOLLISION_CHANNEL_ACTION		ECC_GameTraceChannel1
#define HDCOLLISION_CHANNEL_PROJECTILE	ECC_GameTraceChannel3
#define HDCOLLISION_CHANNEL_PLAYER		ECC_GameTraceChannel4
#define HDCOLLISION_CHANNEL_HELLPOD		ECC_GameTraceChannel5
#define HDCOLLISION_CHANNEL_STRATAGEM	ECC_GameTraceChannel6