
#include "HDGameplayTag.h"

UE_DEFINE_GAMEPLAY_TAG(Tag_Character_Action_StratagemInputMode,   "Character.Action.StratagemInputMode ");
UE_DEFINE_GAMEPLAY_TAG(Tag_Character_Action_HoldStratagem,        "Character.Action.HoldStratagem ");
UE_DEFINE_GAMEPLAY_TAG(Tag_Character_Action_DetachStratagem,      "Character.Action.DetachStratagem ");
UE_DEFINE_GAMEPLAY_TAG(Tag_Character_Action_ThrowEnd,             "Character.Action.ThrowEnd ");
UE_DEFINE_GAMEPLAY_TAG(Tag_Character_Action_Dead,                 "Character.State.Dead ");
UE_DEFINE_GAMEPLAY_TAG(Tag_Block_All,                             "Block.All");
UE_DEFINE_GAMEPLAY_TAG(Tag_Block_Move,                            "Block.Move");
UE_DEFINE_GAMEPLAY_TAG(Tag_Block_Fire,                            "Block.Fire");
UE_DEFINE_GAMEPLAY_TAG(Tag_Block_Reload,                          "Block.Reload");
UE_DEFINE_GAMEPLAY_TAG(Tag_Block_Grenade,                         "Block.Grenade");
UE_DEFINE_GAMEPLAY_TAG(Tag_Block_Stratagem,                       "Block.Stratagem");
UE_DEFINE_GAMEPLAY_TAG(Tag_Block_Minimap,                         "Block.Minimap");
UE_DEFINE_GAMEPLAY_TAG(Tag_Input,                                 "Input");
UE_DEFINE_GAMEPLAY_TAG(Tag_Trigger_Aiming,                        "Trigger.Aiming");
UE_DEFINE_GAMEPLAY_TAG(Tag_Trigger_Shoulder,                      "Trigger.Shoulder");
UE_DEFINE_GAMEPLAY_TAG(Tag_Trigger_Sprint,                        "Trigger.Sprint");
UE_DEFINE_GAMEPLAY_TAG(Tag_Trigger_Crouch,                        "Trigger.Crouch");
UE_DEFINE_GAMEPLAY_TAG(Tag_Trigger_Prone,                         "Trigger.Prone");
UE_DEFINE_GAMEPLAY_TAG(Tag_Trigger_Attack,                        "Trigger.Attack");
UE_DEFINE_GAMEPLAY_TAG(Tag_Trigger_Reload,                        "Trigger.Reload");
UE_DEFINE_GAMEPLAY_TAG(Tag_Trigger_RegenStamina,                  "Trigger.RegenStamina");
UE_DEFINE_GAMEPLAY_TAG(Tag_Trigger_StratagemInputMode,            "Trigger.StratagemInputMode");
UE_DEFINE_GAMEPLAY_TAG(Tag_Trigger_ThrowStratagem,                "Trigger.ThrowStratagem");
UE_DEFINE_GAMEPLAY_TAG(Tag_Event_StratagemHUD,                    "Event.StratagemHUD");
UE_DEFINE_GAMEPLAY_TAG(Tag_Event_StratagemHUD_Active,             "Event.StratagemHUD.Active");
UE_DEFINE_GAMEPLAY_TAG(Tag_Event_StratagemHUD_Deactive,           "Event.StratagemHUD.Deactive");
UE_DEFINE_GAMEPLAY_TAG(Tag_Event_StratagemHUD_AddCommand,         "Event.StratagemHUD.AddCommand");
UE_DEFINE_GAMEPLAY_TAG(Tag_Event_PlayerHUD,                       "Event.PlayerHUD");
UE_DEFINE_GAMEPLAY_TAG(Tag_Event_PlayerHUD_CurrentAmmoChange,     "Event.PlayerHUD.CurrentAmmoChange");
UE_DEFINE_GAMEPLAY_TAG(Tag_Event_PlayerHUD_MaxAmmoChange,         "Event.PlayerHUD.MaxAmmoChange");
UE_DEFINE_GAMEPLAY_TAG(Tag_Event_PlayerHUD_CurrentCapacityChange, "Event.PlayerHUD.CurrentCapacityChange");
UE_DEFINE_GAMEPLAY_TAG(Tag_Event_PlayerHUD_MaxCapacityChange,     "Event.PlayerHUD.MaxCapacityChange");
UE_DEFINE_GAMEPLAY_TAG(Tag_Event_PlayerHUD_Initialize,            "Event.PlayerHUD.Initialize");
UE_DEFINE_GAMEPLAY_TAG(Tag_Event_PlayerHUD_EquipWeapon,           "Event.PlayerHUD.EquipWeapon");
UE_DEFINE_GAMEPLAY_TAG(Tag_Event_Spawn_Projectile,                "Event.Spawn.Projectile");
UE_DEFINE_GAMEPLAY_TAG(Tag_Event_Reload,                          "Event.Reload");
UE_DEFINE_GAMEPLAY_TAG(Tag_Data_Damage_Projectile,                "Data.Damage.Projectile");
UE_DEFINE_GAMEPLAY_TAG(Tag_Data_DotDamage_TickDamage,             "Data.DotDamage.TickDamage");
UE_DEFINE_GAMEPLAY_TAG(Tag_Data_Projectile_StatusEffectDuration,  "Data.Projectile.StatusEffectDuration");
UE_DEFINE_GAMEPLAY_TAG(Tag_Data_Attribute,                        "Data.Attribute");
UE_DEFINE_GAMEPLAY_TAG(Tag_Data_Attribute_Ammo,                   "Data.Attribute.Ammo");
UE_DEFINE_GAMEPLAY_TAG(Tag_Data_Attribute_MaxAmmo,                "Data.Attribute.MaxAmmo");
UE_DEFINE_GAMEPLAY_TAG(Tag_Data_Attribute_Capacity,               "Data.Attribute.Capacity");
UE_DEFINE_GAMEPLAY_TAG(Tag_Data_Attribute_MaxCapacity,            "Data.Attribute.MaxCapacity");
UE_DEFINE_GAMEPLAY_TAG(Tag_Data_Knockback_Hit,                    "Data.Knockback.Hit");
UE_DEFINE_GAMEPLAY_TAG(Tag_Data_Knockback_Ragdoll,                "Data.Knockback.Ragdoll");
UE_DEFINE_GAMEPLAY_TAG(Tag_Cost_Stamina,                          "Cost.Stamina");
UE_DEFINE_GAMEPLAY_TAG(Tag_Regen_Stamina,                         "Regen.Stamina");
