#pragma once

#define HDMONTAGE_SECTIONNAME_RIFLE_AIM		FName("Rifle_Aim")
#define HDMONTAGE_SECTIONNAME_RIFLE_HIP		FName("Rifle_Hip")
#define HDMONTAGE_SECTIONNAME_PISTOL		FName("Pistol")
#define HDMONTAGE_SECTIONNAME_SHOTGUN_AIM	FName("Shotgun_Aim")
#define HDMONTAGE_SECTIONNAME_SHOTGUN_HIP	FName("Shotgun_Hip")
#define HDMONTAGE_SECTIONNAME_RIFLE_PRONE	FName("Rifle_Prone")
#define HDMONTAGE_SECTIONNAME_SHOTGUN_PRONE FName("Shotgun_Prone")